### PR TITLE
build: fix --enable-openssl support

### PR DESCRIPTION
**Pull request by schubi2**
Added --enable-openssl build and fixed regarding issues around --stringparam profile.condition settings.

.github/workflows/ci.yml: added openssl builds
Make.xml.rules.in: fixed double profile.condition settings
configure.ac: fixed double profile.condition settings
ci/run-build-and-tests.sh: added openssl builds

This should solve issue:
https://github.com/linux-pam/linux-pam/issues/553

### CODE REVIEW

**Comment by ldv-alt** [comment]
Do we really have to use `profile.condition` for different options?

**Comment by schubi2** [comment]
> Do we really have to use `profile.condition` for different options?

Yes, currently I see 3. Using vendordir, libeconf and openssl.

Hm, now I see another issue around openssl in the build:
2023-04-06T12:00:22.6874877Z libtool: link: gcc-12 -I../../../../libpam/include -I../../../../libpamc/include -W -Wall -Wbad-function-cast -Wcast-align -Wcast-align=strict -Wcast-qual -Wdeprecated -Wformat=2 -Winit-self -Winline -Wmain -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wnull-dereference -Wpointer-arith -Wreturn-type -Wshadow -Wstrict-prototypes -Wundef -Wuninitialized -Wunused -Wwrite-strings -Werror -g -O2 -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -o .libs/hmacfile hmac_openssl_wrapper.o  ../../libpam/.libs/libpam.so -Wl,-rpath -Wl,/home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_inst/lib
2023-04-06T12:00:22.7062999Z /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start':
2023-04-06T12:00:22.7064369Z (.text+0x1b): undefined reference to `main'
2023-04-06T12:00:22.7066682Z /usr/bin/ld: hmac_openssl_wrapper.o: in function `hmac_size':
2023-04-06T12:00:22.7067751Z /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:325: undefined reference to `OSSL_PARAM_construct_utf8_string'
2023-04-06T12:00:22.7068866Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:329: undefined reference to `EVP_MAC_fetch'
2023-04-06T12:00:22.7069956Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:335: undefined reference to `EVP_MAC_CTX_new'
2023-04-06T12:00:22.7072442Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:341: undefined reference to `EVP_MAC_init'
2023-04-06T12:00:22.7073448Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:347: undefined reference to `EVP_MAC_CTX_get_mac_size'
2023-04-06T12:00:22.7074767Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:352: undefined reference to `EVP_MAC_CTX_free'
2023-04-06T12:00:22.7075814Z /usr/bin/ld: /home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_build/sub/modules/pam_timestamp/../../../../modules/pam_timestamp/hmac_openssl_wrapper.c:355: undefined reference to `EVP_MAC_free'

**Comment by ldv-alt** [comment]
> Hm, now I see another issue around openssl in the build: 2023-04-06T12:00:22.6874877Z libtool: link: gcc-12 -I../../../../libpam/include -I../../../../libpamc/include -W -Wall -Wbad-function-cast -Wcast-align -Wcast-align=strict -Wcast-qual -Wdeprecated -Wformat=2 -Winit-self -Winline -Wmain -Wmissing-declarations -Wmissing-format-attribute -Wmissing-prototypes -Wnull-dereference -Wpointer-arith -Wreturn-type -Wshadow -Wstrict-prototypes -Wundef -Wuninitialized -Wunused -Wwrite-strings -Werror -g -O2 -Wl,--as-needed -Wl,--no-undefined -Wl,-O1 -o .libs/hmacfile hmac_openssl_wrapper.o ../../libpam/.libs/libpam.so -Wl,-rpath -Wl,/home/runner/work/linux-pam/linux-pam/Linux-PAM-1.5.2/_inst/lib 2023-04-06T12:00:22.7062999Z /usr/bin/ld: /usr/lib/gcc/x86_64-linux-gnu/12/../../../x86_64-linux-gnu/Scrt1.o: in function `_start': 2023-04-06T12:00:22.7064369Z (.text+0x1b): undefined reference to `main' 

Looks like it never worked. @ikerexxe, please have a look,
```
if COND_USE_OPENSSL
hmacfile_SOURCES = hmac_openssl_wrapper.c
else
hmacfile_SOURCES = hmacfile.c hmacsha1.c sha1.c
endif
```
seems to be wrong.

**Comment by schubi2** [comment]
> > > Do we really have to use `profile.condition` for different options?
> > 
> > 
> > Yes, currently I see 3. Using vendordir, libeconf and openssl.
> 
> I wish we wouldn't use the same --stringparam for different options, it isn't just look ugly but also causes bugs like #553.

Is there another way to define conditional tags in e.g. man pages ?

**Comment by ldv-alt** [comment]
> > > > Do we really have to use `profile.condition` for different options?
> > > 
> > > 
> > > Yes, currently I see 3. Using vendordir, libeconf and openssl.
> > 
> > 
> > I wish we wouldn't use the same --stringparam for different options, it isn't just look ugly but also causes bugs like #553.
> 
> Is there another way to define conditional tags in e.g. man pages ?

I'm definitely not an expert in this area but it seems to me that we already use --stringparam with different options, see
`git grep -e --stringparam`.

**Comment by ikerexxe** [comment]
Some changes need to be made in `Makefile.am` to fix this problem. Should I open a new PR or can they be included in this one?

Patch:
```
diff --git a/modules/pam_timestamp/Makefile.am b/modules/pam_timestamp/Makefile.am
index bc2f3617..27d61237 100644
--- a/modules/pam_timestamp/Makefile.am
+++ b/modules/pam_timestamp/Makefile.am
@@ -49,14 +49,11 @@ pam_timestamp_check_CFLAGS = $(AM_CFLAGS) @EXE_CFLAGS@
 pam_timestamp_check_LDADD = $(top_builddir)/libpam/libpam.la $(SYSTEMD_LIBS)
 pam_timestamp_check_LDFLAGS = @EXE_LDFLAGS@
 
-if COND_USE_OPENSSL
-hmacfile_SOURCES = hmac_openssl_wrapper.c
-else
+if !COND_USE_OPENSSL
 hmacfile_SOURCES = hmacfile.c hmacsha1.c sha1.c
-endif
 hmacfile_LDADD = $(top_builddir)/libpam/libpam.la
-
 check_PROGRAMS = hmacfile
+endif
 
 if ENABLE_REGENERATE_MAN
 dist_noinst_DATA = README
```

**Comment by schubi2** [comment]
> It's fine for me to include it here. @schubi2 do you mind adding the patch to the PR?

It is absolutely OK. Just ping me if I can help.

**Comment by schubi2** [comment]
> It's fine for me to include it here. @schubi2 do you mind adding the patch to the PR?
I have added you to my repo in order to make changes. So you can make it directly.

**Comment by ikerexxe** [comment]
> I have added you to my repo in order to make changes. So you can make it directly.

Perfect! I pushed my changes there and the CI is green, so this is ready for review.

**Review by ldv-alt — CHANGES_REQUESTED** [review]
Also, please keep the ci part of the change as a separate commit,
you could just take it from `ldv/ci-openssl` branch.

**Review by ldv-alt — APPROVED** [review]

**Pull request merged**
