### PR TITLE
Fix a typo in the documentation

### PR DESCRIPTION
**Pull request by sbraz**
Hi, just a simple typo fix (with a preposition changed too).

### CODE REVIEW

**Comment by ldv-alt** [comment]
There is one more typo in that sentence that needs to be fixed. :)

**Comment by sbraz** [comment]
@ldv-alt you mean "does"? I kept it because I read it as "the way that Solaris' PAM does" without the parentheses.

**Comment by t8m** [comment]
No, it is the 'derivitives'.

**Comment by sbraz** [comment]
Thanks, I couldn't even see it :)

**Pull request merged**
