### PR TITLE
doc: Update PAM documentation from DockBook 4 to DocBook 5

### PR DESCRIPTION
**Pull request by schubi2**
Make.xml.rules.in:
- Using RNG file instead of DTD file for checking XML files.
- Taking the correct stylesheet for README files.

doc/sag/Makefile.am, doc/adg/Makefile.am, doc/mwg/Makefile.am:
- Using RNG file instead of DTD file for checking XML files.

configure.ac:
- Adding a new option for selecting RNG check file (-enable-docbook-rng)
- Switching stylesheets to docbook 5
- Checking DocBook 5 environment instead of DocBook 4 environment

*.xml:
Update from DockBook 4 to DocBook 5

### CODE REVIEW

**Review by ldv-alt — CHANGES_REQUESTED** [review]
I haven't looked into the changes yet, but the quality of the commit message is unacceptable, what's written in the PR has to be written in the commit message itself.

**Comment by schubi2** [comment]
> I haven't looked into the changes yet, but the quality of the commit message is unacceptable, what's written in the PR has to be written in the commit message itself.

I am struggling a little bit with git. The second commit is merge without any content and I cannot get rid of it. 
"git rebase -i HEAD~10" does not show it. Do I have to remove this commit somehow or will it be deleted while the merge ?

**Comment by schubi2** [comment]
> I haven't looked into the changes yet, but the quality of the commit message is unacceptable, what's written in the PR has to be written in the commit message itself.

Yes, i have struggled a little bit with git. I hope, that it OK now.

**Review by ldv-alt — CHANGES_REQUESTED** [review]
Could you include the PR description into the commit message, please?

**Comment by schubi2** [comment]
> Could you include the PR description into the commit message, please?

Yes, I have added them.

**Review by thkukuk — CHANGES_REQUESTED** [review]
@schubi2 Please remove the zanata.xml changes, this file is for translations, not documentation.

**Comment by thkukuk** [comment]
examples/.gitignore should also be a separate PR.

**Comment by thkukuk** [comment]
README.pam_tty_audit is empty

**Comment by schubi2** [comment]
I have update it. Thanks for the feedback !

**Review by thkukuk — APPROVED** [review]
Looks good now, and the format issues from docbook4 are gone with docbook5, too.

**Comment by thkukuk** [comment]
@ldv-alt all my issues are solved, are you now happy with the commit message and can we merge this?

**Review by ldv-alt — APPROVED** [review]

**Comment by ldv-alt** [comment]
I'm not one of those who is able to review these changes properly, so let's merge this.

**Pull request merged**
