### PR TITLE
Fix build with musl libc.

### PR DESCRIPTION
**Pull request by jameshilliard**

### CODE REVIEW

**Comment by ldv-alt** [comment]
I think we shouldn't emulate fgetpwent_r.

**Comment by jameshilliard** [comment]
I guess #234 probably is a better fix.

**Comment by ldv-alt** [comment]
On Thu, Jun 11, 2020 at 10:09:59AM -0700, James Hilliard wrote:
> I guess #234 probably is a better fix.

Sorry?

**Comment by jameshilliard** [comment]
Oh, sorry, meant #237.

**Pull request closed without merging**
