### PR TITLE
pam_exec: check if user name is already available during auth

### PR DESCRIPTION
**Pull request by user318**
On second and futher iterations, pam_exec module is called
before the login prompt and thus command is called without
a user name. This fix asks PAM for the user name when type
is auth.
This fix addresses the issue #131.

### CODE REVIEW

**Comment by user318** [comment]
Accidentally removed the branch from my repo for a short time. This cause the PR closed.

**Comment by user318** [comment]
Fixed patch to compile with `-Werror` - it would be two patches with fixes, that is why I updated the whole branch with new version of the patch.

**Comment by ldv-alt** [comment]
Although pam_exec can work without username, the subsequent absence of PAM_USER environment variable can indeed make the called program upset.

The mentioning of "On second and futher iterations" in the commit message is very misleading, though.  Apparently, it describes the behaviour of an application not mentioned in the commit message.

I don't mind accepting this change, but could you reword the commit message, squash commits into a single one, and rebase it on top of the current master branch, please?

**Comment by user318** [comment]
Hmm, I did not do many tests, but in my setup I was getting the behaviour like I described. The first invocation of pam_exec was getting a username for some reason. So I was asked for the username in the terminal before pam_exec invocation. And after failed attempt - futher invocation was not asking for the username. But of course, I can rephrase it. :)

**Comment by ldv-alt** [comment]
Most applications do not iterate this way at all.

**Comment by user318** [comment]
Updated the branch with your suggestions. Please check if it is OK now.

**Comment by ldv-alt** [comment]
On Mon, Mar 23, 2020 at 10:23:29AM -0700, Alexander Zubkov wrote:
> Updated the branch with your suggestions. Please check if it is OK now.

Would it make sense to extend the change beyond auth stage?
For example, what if pam_exec is invoked at another stage and nothing has requested a user name before?

I'd also suggest to replace "login" with "user name" in the commit message.

**Comment by user318** [comment]
> Would it make sense to extend the change beyond auth stage? For example, what if pam_exec is invoked at another stage and nothing has requested a user name before?

Yes, you are right. I agree that it should make sence for other types too. I just used it for auth myself and did not want to meddle much.

> I'd also suggest to replace "login" with "user name" in the commit message.

OK. I'll make a new branch with these changes.

**Comment by ldv-alt** [comment]
On Mon, Mar 23, 2020 at 11:07:20AM -0700, Alexander Zubkov wrote:
> > I'd also suggest to replace "login" with "user name" in the commit message.
> 
> OK. I'll make a new branch with these changes.

Thanks.  There is no need for a new branch, I suppose you can just amend this one.

**Comment by user318** [comment]
> Thanks.  There is no need for a new branch, I suppose you can just amend this one.

No problem with a new branch forced push. Anyway you suggested to imrove the description.
I had to rename one further usage of the retval variable, because now without "if" I had to define retval in the top level scope of the function body and that would cause an error with "-Werror".

**Comment by oxr463** [comment]
@user318 what are you using to test? I would recommend providing an example of what you mean via [`pamtester`](http://pamtester.sourceforge.net).

**Comment by user318** [comment]
> @user318 what are you using to test?

@oxr463 It was agetty and me trying to login via serial console. :)

**Comment by user318** [comment]
As I see pamtester takes username on its command line. And I suppose it may not be suitable to test this. Because it should be able to prompt for the user name. The idea is if the main program has not still requested the username from the user while calling the pam_exec module, that it will do it when the module asks pam for the user name.
Probably my getty version makes 3 tries to authenticate and first time it prompts for the username on its own before running pam, but during further tries it does not do it in advance, but only when the module requests it from pam.

**Pull request closed without merging**
