### PR TITLE
man: clarify PAM_DATA_SILENT in pam_set_data.3

### PR DESCRIPTION
**Pull request by bluca**
pam_end.3 has additional and important information about PAM_DATA_SILENT, copy it to pam_set_data.3 since that describes the cleanup callback where it will be set.

### CODE REVIEW

**Review by t8m — APPROVED** [review]

**Comment by poettering** [comment]
Google pointed me to this piece of documentation first btw:

https://github.com/linux-pam/linux-pam/blob/master/doc/adg/Linux-PAM_ADG.xml#L232

Probably should receive similar treatment

**Comment by bluca** [comment]
> Google pointed me to this piece of documentation first btw:
> 
> https://github.com/linux-pam/linux-pam/blob/master/doc/adg/Linux-PAM_ADG.xml#L232
> 
> Probably should receive similar treatment

That's `PAM_SILENT`, not `PAM_DATA_SILENT`, I think they are different things?

**Comment by poettering** [comment]
oh.

(that said, the fact that pam_end() is supposed to be called from the child with PAM_DATA_SILENT still deserves to be mentioned there)

**Comment by bluca** [comment]
> oh.
> 
> (that said, the fact that pam_end() is supposed to be called from the child with PAM_DATA_SILENT still deserves to be mentioned there)

The pam_end manpage already says that, and it is pulled in the PAM_ADG document when it gets built. The XML in the repository is only part of it, it is assembled when it's built and published.

**Pull request merged**
