### PR TITLE
Prepare for the next release

### PR DESCRIPTION
**Pull request by ldv-alt**
The latest release was made almost 5 months ago, let's prepare for the next one.

### CODE REVIEW

**Comment by t8m** [comment]
Hmm, if we are already removing the modules, the new release should be 1.5.0. Or we can do 1.4.1 still with the modules kept and then immediately remove the modules from master which make it clear that they won't be in the next release.

**Comment by ldv-alt** [comment]
On Mon, Nov 02, 2020 at 02:50:33AM -0800, Tomáš Mráz wrote:
> Hmm, if we are already removing the modules, the new release should be 1.5.0. Or we can do 1.4.1 still with the modules kept and then immediately remove the modules from master which make it clear that they won't be in the next release.

I don't mind keeping these modules a bit longer, but there was a
deprecation warning in the NEWS entry for 1.4.0 saying that these modules
are no longer built by default and will be removed in the next release,
so keeping them in the next release would send a misleading message
to the users.

**Comment by t8m** [comment]
OK, then we have to call the release 1.5.0 as removing a module is not a minor update.

**Comment by ldv-alt** [comment]
We have a reference to 1.4.1:
```
$ git grep -F 1.4.1
libpam/libpam.map:LIBPAM_MODUTIL_1.4.1 {
```
I suggest to leave it unchanged since users of this LIBPAM_MODUTIL_1.4.1 interface already exist.

**Comment by t8m** [comment]
that's IMO no problem to keep that reference.

**Review by t8m — APPROVED** [review]

**Comment by ldv-alt** [comment]
OK, master is ready for the next release then.

**Comment by t8m** [comment]
@ldv-alt will you do the release?

**Comment by ldv-alt** [comment]
On Tue, Nov 03, 2020 at 08:09:03AM -0800, Tomáš Mráz wrote:
> @ldv-alt will you do the release?

I could do the release tomorrow.

**Comment by t8m** [comment]
Are we ready for the release now?

**Comment by ldv-alt** [comment]
Done.

**Pull request merged**
