### PR TITLE
pam_wheel: improve coding logic

### PR DESCRIPTION
**Pull request by whzhe51**
Signed-off-by: whzhe <wanghongzhe@huawei.com>

### CODE REVIEW

**Comment by t8m** [comment]
I am sorry but I do not see any improvement here. Could you be please more specific in what you're trying to achieve by the change?

**Comment by whzhe51** [comment]
> I am sorry but I do not see any improvement here. Could you be please more specific in what you're trying to achieve by the change?

There are two times if (fromsu == NULL), i think it's redundant.And i just merge into one

**Comment by t8m** [comment]
But you are duplicating other stuff due to that. That does not look like an improvement to me, I am sorry.

**Comment by t8m** [comment]
Also you're really breaking the logic as fromsu can be assigned there.

**Pull request closed without merging**
